---
  - name: "load zomboid server save"
    hosts: zomboid
    vars:
      ansible_remote_tmp: /tmp/
      server_admin_user: "steam"
      # seems to have a lot of perm issue in other directory
      server_config_path: "/home/{{ server_admin_user }}/update_zomboid.txt"
      server_files_path: "/home/{{ server_admin_user }}/zomboid"
      save_files_s_path: "/home/{{ server_admin_user }}/Zomboid/Server"
      save_files_mp_path: "/home/{{ server_admin_user }}/Zomboid/Saves"
      cloud_provider: "hetzner" # or aws
      local_file_backup_base_path: /mnt/c/Users/Yukari/Documents/zomboid_saves
    tasks:
      - include_tasks: ./tasks/install_gameserver.yml

    # run the server with bash start-server.sh (runs as a daemon)